[project]
name = "codfreq"

[tool.mypy]
python_version = '3.13'
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_no_return = true
warn_unreachable = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
plugins = "pydantic.mypy"

[build-system]
requires = ["setuptools", "wheel", "cython"]
build-backend = "setuptools.build_meta:__legacy__"
