#! /bin/bash

set -e

USAGE="command usage: $(basename $0) -r <PROFILE_PATH> -d <FASTQ_DIRECTORY>"


while getopts ':r:d:' OPT; do
    case "$OPT" in
        r)
            PROFILE=$OPTARG
            ;;
        d)
            WORKDIR=$OPTARG
            ;;
        \?)
            echo $USAGE >&2
            exit 0
            ;;
        :) echo "Missing option argument for -$OPTARG\n$USAGE" >&2; exit 1;;
        *) echo "Unimplemented option: -$OPTARG\n$USAGE" >&2; exit 1;;
    esac
done

if [ -z $PROFILE ]; then
    echo "Missing required option argument -r <PROFILE_PATH>" >&2
    exit 1
fi

if [ -z $WORKDIR ]; then
    echo "Missing required option argument -d <FASTQ_DIRECTORY>" >&2
    exit 1
fi

if [ ! -f $PROFILE ]; then
    echo "Value of -r <PROFILE> is not a valid file" >&2
    exit 1
fi

PROFILE="$(realpath $PROFILE)" || echo $USAGE || false
WORKDIR="$(realpath $WORKDIR)" || echo $USAGE || false

docker run \
    -it --rm \
    --mount type=bind,source="$PROFILE",target=/tmp/profile.json \
    --mount type=bind,source="$WORKDIR",target=/fastqfiles \
    hivdb/codfreq-runner:latest \
    bin/align-all-local -r /tmp/profile.json -d /fastqfiles
