#! /bin/bash

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <ACCESSION_FILE>" >&2
    exit 1
fi

WORKDIR=$PWD/$(echo $1 | rev | cut -d "." -f2- | rev)
mkdir -p $WORKDIR
cd $WORKDIR
for acc in $(cat $PWD/$1); do
   fastq-dump -I --split-files --gzip $acc
done
