#! /bin/bash

set -e


SKIP_EXISTS=false
NPROCALL=`nproc --all`
NTHREADS=$(($NPROCALL * 19 / 20))
USAGE="command usage: $(basename $0) [-s] [-n NTHREADS] <DIRECTORY>"
SCRIPTDIR="$(realpath $(dirname $0))"


while getopts ':sn:' OPT; do
    case "$OPT" in
        s)
            SKIP_EXISTS=true
            ;;
        n)
            NTHREADS=$OPTARG
            ;;
        \?)
            echo $USAGE >&2
            exit 0
            ;;
        :)
            echo -e "Missing option argument for -$OPTARG\n$USAGE" >&2
            exit 2
            ;;
        *)
            echo -e "Unimplemented option: -$OPTARG\n$USAGE" >&2
            exit 3
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ -z "$1" ]; then
    echo -e "Missing parameter DIRECTORY\n$USAGE" >&2
    exit 1
fi

NTHREADS=$(($NTHREADS > 0 ? $NTHREADS : 1))
export NTHREADS=$(($NTHREADS < $NPROCALL ? $NTHREADS : $NPROCALL - 1))

knowns=""
while [ -n "$1" ]; do
    directory=$(realpath $1)
    for filename in `find $directory -name "*.sam" -o -name "*.bam"`; do
        noext=$(echo $filename | sed -r "s/\.[bs]am$//g")
        knowns="$known $noext"
        nucfishout="$noext.nucfish"
        if $SKIP_EXISTS && [ -f $nucfishout ]; then
            echo "Skipped: $noext"
            continue
        fi
        python3 ${SCRIPTDIR}/sam2nucfish.py $filename $nucfishout | tee -a $noext.log
    done
    shift
done
