#! /bin/bash

set -e


VERBOSE=false
SKIP_EXISTS=false
NPROCALL=`nproc --all`
NTHREADS=$(($NPROCALL * 19 / 20))
USAGE="command usage: $(basename $0) [-sv] [-n NTHREADS] <DIRECTORY>"
SCRIPTDIR="$(realpath $(dirname $0))"


while getopts ':svn:' OPT; do
    case "$OPT" in
        v)
            VERBOSE=true
            ;;
        s)
            SKIP_EXISTS=true
            ;;
        n)
            NTHREADS=$OPTARG
            ;;
        \?)
            echo $USAGE >&2
            exit 0
            ;;
        :)
            echo -e "Missing option argument for -$OPTARG\n$USAGE" >&2
            exit 2
            ;;
        *)
            echo -e "Unimplemented option: -$OPTARG\n$USAGE" >&2
            exit 3
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ -z "$1" ]; then
    echo -e "Missing parameter DIRECTORY\n$USAGE" >&2
    exit 1
fi

NTHREADS=$(($NTHREADS > 0 ? $NTHREADS : 1))
export NTHREADS=$(($NTHREADS < $NPROCALL ? $NTHREADS : $NPROCALL - 1))

. ~/.virtualenvs/SRALoader/bin/activate
knowns=""
while [ -n "$1" ]; do
    directory=$(realpath $1)
    for filename in `find $directory -name "*.sam"`; do
        noext=$(echo $filename | sed -r "s/\.sam$//g")
        knowns="$known $noext"
        samout="$noext.sam"
        codfishout="$noext.codfish"
        if $SKIP_EXISTS && [ -f $codfishout ]; then
            echo "Skipped: $noext"
            continue
        fi
        python ${SCRIPTDIR}/sam2codfish.py $samout $codfishout >> $noext.log
        if $VERBOSE; then
            cat $noext.log >&2
        fi
    done
    shift
done
